### ISSUE TITLE
jira_soap.py:get_available_transitions() does not catch errors and throw exceptions as expected

### ISSUE THREAD

**Issue by geoffwhittington** [sdelements/sdetools#65]
NOTE: This was previously captured here: https://github.com/sdelements/SDE-DotNet-Integration/issues/72

In JIRA 4.3.3:

If a Jira project is assigned to another user, too (say add_only) and the wizard is set to update SDE project tasks to Jira when the wizard user is the user then the integration fails with the following issue:
{
INFO: Calling JIRA SOAP method getIssuesFromJqlSearch
DEBUG: + Args: ('xxxxxx', u"project='SPC' AND summary~'T178'",

)
INFO: Calling JIRA SOAP method getAvailableActions
DEBUG: + Args: ('Y91N9uj5eA', 'SPC-16')
Traceback (most recent call last):
File "sde.py", line 35, in 
File "sde.py", line 24, in main
File "sdetools\sdelib\mod_mgr.pyc", line 53, in run_command
File "sdetools\modules\sync_jira__init__.pyc", line 33, in handle
File "sdetools\alm_integration\alm_plugin_base.pyc", line 422, in synchronize
File "sdetools\modules\sync_jira\jira_plugin.pyc", line 96, in alm_update_task_status
File "sdetools\modules\sync_jira\jira_soap.pyc", line 149, in get_available_transitions
TypeError: 'NoneType' object is not iterable
}
Steps (in JIRA 4.3.3):
1. Create a JIRA project
2. Assign a new user to it, say add_only
3. Create a SDE project
4. Using create a new JIRA wizard with the following settings

user: the assigned user (add_only)
authoritative: SDE
Run the wizard
Now, change some SDE project task statuses to DONE or N/A
Run the wizard again Issue: it fails due to the above issue.

**Comment by geoffwhittington** [comment]
Fixed
